

'''
The Unicode Standard 13.0, Copyright © 1991-2020 Unicode, Inc. All rights reserved.
0C80 Kannada 0CEA
0CB6 ಶ KANNADA LETTER SHA
0CB7 ಷ KANNADA LETTER SSA
0CB8 ಸ KANNADA LETTER SA
0CB9 ಹ KANNADA LETTER HA
Various signs
0CBC $಼ KANNADA SIGN NUKTA
0CBD ಽ KANNADA SIGN AVAGRAHA
Dependent vowel signs
0CBE $ಾ KANNADA VOWEL SIGN AA
0CBF $ಿ KANNADA VOWEL SIGN I
0CC0 $ೀ KANNADA VOWEL SIGN II
≡ 0CBF $ಿ   0CD5 $ೕ
0CC1 $ು KANNADA VOWEL SIGN U
0CC2 $ೂ KANNADA VOWEL SIGN UU
0CC3 $ೃ KANNADA VOWEL SIGN VOCALIC R
0CC4 $ೄ KANNADA VOWEL SIGN VOCALIC RR
0CC5 " <reserved>
0CC6 $ೆ KANNADA VOWEL SIGN E
0CC7 $ೇ KANNADA VOWEL SIGN EE
≡ 0CC6 $ೆ  0CD5 $ೕ
0CC8 $ೈ KANNADA VOWEL SIGN AI
≡ 0CC6 $ೆ  0CD6 $ೖ
0CC9 " <reserved>
0CCA $ೊ KANNADA VOWEL SIGN O
≡ 0CC6 $ೆ  0CC2 $ೂ
0CCB $ೋ KANNADA VOWEL SIGN OO
≡ 0CCA $ೊ  0CD5 $ೕ
0CCC $ೌ KANNADA VOWEL SIGN AU
Virama
0CCD $್ KANNADA SIGN VIRAMA
• preferred name is halant
Various signs
0CD5 $ೕ KANNADA LENGTH MARK
0CD6 $ೖ KANNADA AI LENGTH MARK
Additional consonants
0CDE ೞ KANNADA LETTER FA
※ KANNADA LETTER LLLA
• obsolete historic letter
• name is a mistake for LLLA
Additional vowels for Sanskrit
0CE0 ೠ KANNADA LETTER VOCALIC RR
0CE1 ೡ KANNADA LETTER VOCALIC LL
Dependent vowels
0CE2 $ೢ KANNADA VOWEL SIGN VOCALIC L
0CE3 $ೣ KANNADA VOWEL SIGN VOCALIC LL
Reserved
For viram punctuation, use the generic Indic 0964 and 0965.
0CE4 " <reserved>
→ 0964 ।  devanagari danda
0CE5 " <reserved>
→ 0965 ॥  devanagari double danda
Digits
0CE6 ೦ KANNADA DIGIT ZERO
0CE7 ೧ KANNADA DIGIT ONE
0CE8 ೨ KANNADA DIGIT TWO
0CE9 ೩ KANNADA DIGIT THREE
0CEA ೪ KANNADA DIGIT FOUR
Various signs
0C80 ಀ KANNADA SIGN SPACING CANDRABINDU
0C81 $ಁ KANNADA SIGN CANDRABINDU
0C82 $ಂ KANNADA SIGN ANUSVARA
0C83 $ಃ KANNADA SIGN VISARGA
0C84 ಄ KANNADA SIGN SIDDHAM
= siddhirastu
• used at the beginning of texts as an invocation
→ A8FC ꣼  devanagari sign siddham
→ 111DB 𑇛  sharada sign siddham
Independent vowels
0C85 ಅ KANNADA LETTER A
0C86 ಆ KANNADA LETTER AA
0C87 ಇ KANNADA LETTER I
0C88 ಈ KANNADA LETTER II
0C89 ಉ KANNADA LETTER U
0C8A ಊ KANNADA LETTER UU
0C8B ಋ KANNADA LETTER VOCALIC R
0C8C ಌ KANNADA LETTER VOCALIC L
0C8D " <reserved>
0C8E ಎ KANNADA LETTER E
0C8F ಏ KANNADA LETTER EE
0C90 ಐ KANNADA LETTER AI
0C91 " <reserved>
0C92 ಒ KANNADA LETTER O
0C93 ಓ KANNADA LETTER OO
0C94 ಔ KANNADA LETTER AU
Consonants
0C95 ಕ KANNADA LETTER KA
0C96 ಖ KANNADA LETTER KHA
0C97 ಗ KANNADA LETTER GA
0C98 ಘ KANNADA LETTER GHA
0C99 ಙ KANNADA LETTER NGA
0C9A ಚ KANNADA LETTER CA
0C9B ಛ KANNADA LETTER CHA
0C9C ಜ KANNADA LETTER JA
0C9D ಝ KANNADA LETTER JHA
0C9E ಞ KANNADA LETTER NYA
0C9F ಟ KANNADA LETTER TTA
0CA0 ಠ KANNADA LETTER TTHA
0CA1 ಡ KANNADA LETTER DDA
0CA2 ಢ KANNADA LETTER DDHA
0CA3 ಣ KANNADA LETTER NNA
0CA4 ತ KANNADA LETTER TA
0CA5 ಥ KANNADA LETTER THA
0CA6 ದ KANNADA LETTER DA
0CA7 ಧ KANNADA LETTER DHA
0CA8 ನ KANNADA LETTER NA
0CA9 " <reserved>
0CAA ಪ KANNADA LETTER PA
0CAB ಫ KANNADA LETTER PHA
0CAC ಬ KANNADA LETTER BA
0CAD ಭ KANNADA LETTER BHA
0CAE ಮ KANNADA LETTER MA
0CAF ಯ KANNADA LETTER YA
0CB0 ರ KANNADA LETTER RA
0CB1 ಱ KANNADA LETTER RRA
0CB2 ಲ KANNADA LETTER LA
0CB3 ಳ KANNADA LETTER LLA
0CB4 " <reserved>
0CB5 ವ KANNADA LETTER VA

The Unicode Standard 13.0, Copyright © 1991-2020 Unicode, Inc. All rights reserved.
0CEB Kannada 0CF2
0CEB ೫ KANNADA DIGIT FIVE
0CEC ೬ KANNADA DIGIT SIX
0CED ೭ KANNADA DIGIT SEVEN
0CEE ೮ KANNADA DIGIT EIGHT
0CEF ೯ KANNADA DIGIT NINE
Signs used in Sanskrit
0CF1 ೱ KANNADA SIGN JIHVAMULIYA
→ 1CF5 ᳵ  vedic sign jihvamuliya
0CF2 ೲ KANNADA SIGN UPADHMANIYA
→ 1CF6 ᳶ  vedic sign upadhmaniya
'''
