

'''
Various Signs
0C80 KANNADA SIGN SPACING CANDRABINDU
0C81 KANNADA SIGN CANDRABINDU
0C82 KANNADA SIGN ANUSVARA
0C83 KANNADA SIGN VISARGA
0C84 KANNADA SIGN SIDDHAM = siddhirastu • used at the beginning of texts as an invocation → A8FC devanagari sign siddham → 111DB sharada sign siddham

Independent Vowels
0C85 KANNADA LETTER A
0C86 KANNADA LETTER AA
0C87 KANNADA LETTER I
0C88 KANNADA LETTER II
0C89 KANNADA LETTER U
0C8A KANNADA LETTER UU
0C8B KANNADA LETTER VOCALIC R
0C8C KANNADA LETTER VOCALIC L
0C8D " <reserved>
0C8E KANNADA LETTER E
0C8F KANNADA LETTER EE
0C90 KANNADA LETTER AI
0C91 " <reserved>
0C92 KANNADA LETTER O
0C93 KANNADA LETTER OO
0C94 KANNADA LETTER AU

Consonants
0C95 KANNADA LETTER KA
0C96 KANNADA LETTER KHA
0C97 KANNADA LETTER GA
0C98 KANNADA LETTER GHA
0C99 KANNADA LETTER NGA
0C9A KANNADA LETTER CA
0C9B KANNADA LETTER CHA
0C9C KANNADA LETTER JA
0C9D KANNADA LETTER JHA
0C9E KANNADA LETTER NYA
0C9F KANNADA LETTER TTA
0CA0 KANNADA LETTER TTHA
0CA1 KANNADA LETTER DDA
0CA2 KANNADA LETTER DDHA
0CA3 KANNADA LETTER NNA
0CA4 KANNADA LETTER TA
0CA5 KANNADA LETTER THA
0CA6 KANNADA LETTER DA
0CA7 KANNADA LETTER DHA
0CA8 KANNADA LETTER NA
0CA9 " <reserved>
0CAA KANNADA LETTER PA
0CAB KANNADA LETTER PHA
0CAC KANNADA LETTER BA
0CAD KANNADA LETTER BHA
0CAE KANNADA LETTER MA
0CAF KANNADA LETTER YA
0CB0 KANNADA LETTER RA
0CB1 KANNADA LETTER RRA
0CB2 KANNADA LETTER LA
0CB3 KANNADA LETTER LLA
0CB4 " <reserved>
0CB5 KANNADA LETTER VA
0CB6 KANNADA LETTER SHA
0CB7 KANNADA LETTER SSA
0CB8 KANNADA LETTER SA
0CB9 KANNADA LETTER HA

Various signs
0CBC ANNADA SIGN NUKTA
0CBD KANNADA SIGN AVAGRAHA

Dependent vowel signs
0CBE ANNADA VOWEL SIGN AA
0CBF ANNADA VOWEL SIGN I
0CC0 ANNADA VOWEL SIGN II ≡ 0CBF  0CD5
0CC1 ANNADA VOWEL SIGN U
0CC2 ANNADA VOWEL SIGN UU
0CC3 ANNADA VOWEL SIGN VOCALIC R
0CC4 ANNADA VOWEL SIGN VOCALIC RR
0CC5 " <reserved>
0CC6 ANNADA VOWEL SIGN E
0CC7 KANNADA VOWEL SIGN EE ≡ 0CC6 $ೆ  0CD5 $ೕ
0CC8 $ೈ KANNADA VOWEL SIGN AI ≡ 0CC6 $ೆ  0CD6 $ೖ
0CC9 " <reserved>
0CCA ANNADA VOWEL SIGN O ≡ 0CC6 $ೆ  0CC2 $ೂ
0CCB ANNADA VOWEL SIGN OO ≡ 0CCA $ೊ  0CD5 $ೕ
0CCC ANNADA VOWEL SIGN AU Virama
0CCD ANNADA SIGN VIRAMA • preferred name is halant

Various signs
0CD5 ANNADA LENGTH MARK
0CD6 ANNADA AI LENGTH MARK

Additional consonants
0CDE ೞ KANNADA LETTER FA
※ KANNADA LETTER LLLA
• obsolete historic letter
• name is a mistake for LLLA
Additional vowels for Sanskrit
0CE0 ೠ KANNADA LETTER VOCALIC RR
0CE1 ೡ KANNADA LETTER VOCALIC LL
Dependent vowels
0CE2 $ೢ KANNADA VOWEL SIGN VOCALIC L
0CE3 $ೣ KANNADA VOWEL SIGN VOCALIC LL
Reserved
For viram punctuation, use the generic Indic 0964 and 0965.
0CE4 " <reserved>
→ 0964 ।  devanagari danda
0CE5 " <reserved>
→ 0965 ॥  devanagari double danda

'''
