

'''
The Unicode Standard 13.0, Copyright © 1991-2020 Unicode, Inc. All rights reserved.
ABC0 Meetei Mayek ABF9
ABDF ꯟ MEETEI MAYEK LETTER NA LONSUM
= n
ABE0 ꯠ MEETEI MAYEK LETTER TIL LONSUM
= t
ABE1 ꯡ MEETEI MAYEK LETTER NGOU LONSUM
= ng
ABE2 ꯢ MEETEI MAYEK LETTER I LONSUM
= i
Dependent vowel signs
ABE3 $ꯣ MEETEI MAYEK VOWEL SIGN ONAP
= o
ABE4 $ꯤ MEETEI MAYEK VOWEL SIGN INAP
= i
ABE5 $ꯥ MEETEI MAYEK VOWEL SIGN ANAP
= aa
ABE6 $ꯦ MEETEI MAYEK VOWEL SIGN YENAP
= e
ABE7 $ꯧ MEETEI MAYEK VOWEL SIGN SOUNAP
= ou
ABE8 $ꯨ MEETEI MAYEK VOWEL SIGN UNAP
= u
ABE9 $ꯩ MEETEI MAYEK VOWEL SIGN CHEINAP
= ei
ABEA $ꯪ MEETEI MAYEK VOWEL SIGN NUNG
= anusvara
Punctuation
ABEB ꯫ MEETEI MAYEK CHEIKHEI
= double danda
ABEC $꯬ MEETEI MAYEK LUM IYEK
= heavy tone
ABED $꯭ MEETEI MAYEK APUN IYEK
= killer
→ 103A $်  myanmar sign asat
Digits
ABF0 ꯰ MEETEI MAYEK DIGIT ZERO
= phun
ABF1 ꯱ MEETEI MAYEK DIGIT ONE
= ama
ABF2 ꯲ MEETEI MAYEK DIGIT TWO
= ani
ABF3 ꯳ MEETEI MAYEK DIGIT THREE
= ahum
ABF4 ꯴ MEETEI MAYEK DIGIT FOUR
= mari
ABF5 ꯵ MEETEI MAYEK DIGIT FIVE
= manga
ABF6 ꯶ MEETEI MAYEK DIGIT SIX
= taruk
ABF7 ꯷ MEETEI MAYEK DIGIT SEVEN
= taret
ABF8 ꯸ MEETEI MAYEK DIGIT EIGHT
= nipal
ABF9 ꯹ MEETEI MAYEK DIGIT NINE
= mapal
The name "Meetei Mayek" is used in official documentation in
Manipur. Many linguists also use the name "Meitei Mayek",
and other transliterations also occur.
Letters
ABC0 ꯀ MEETEI MAYEK LETTER KOK
= ka
ABC1 ꯁ MEETEI MAYEK LETTER SAM
= sa
ABC2 ꯂ MEETEI MAYEK LETTER LAI
= la
ABC3 ꯃ MEETEI MAYEK LETTER MIT
= ma
ABC4 ꯄ MEETEI MAYEK LETTER PA
ABC5 ꯅ MEETEI MAYEK LETTER NA
ABC6 ꯆ MEETEI MAYEK LETTER CHIL
= ca
ABC7 ꯇ MEETEI MAYEK LETTER TIL
= ta
ABC8 ꯈ MEETEI MAYEK LETTER KHOU
= kha
ABC9 ꯉ MEETEI MAYEK LETTER NGOU
= nga
ABCA ꯊ MEETEI MAYEK LETTER THOU
= tha
ABCB ꯋ MEETEI MAYEK LETTER WAI
= wa
ABCC ꯌ MEETEI MAYEK LETTER YANG
= ya
ABCD ꯍ MEETEI MAYEK LETTER HUK
= ha
ABCE ꯎ MEETEI MAYEK LETTER UN
= u
ABCF ꯏ MEETEI MAYEK LETTER I
ABD0 ꯐ MEETEI MAYEK LETTER PHAM
= pha
ABD1 ꯑ MEETEI MAYEK LETTER ATIYA
= a
ABD2 ꯒ MEETEI MAYEK LETTER GOK
= ga
ABD3 ꯓ MEETEI MAYEK LETTER JHAM
= jha
ABD4 ꯔ MEETEI MAYEK LETTER RAI
= ra
ABD5 ꯕ MEETEI MAYEK LETTER BA
ABD6 ꯖ MEETEI MAYEK LETTER JIL
= ja
ABD7 ꯗ MEETEI MAYEK LETTER DIL
= da
ABD8 ꯘ MEETEI MAYEK LETTER GHOU
= gha
ABD9 ꯙ MEETEI MAYEK LETTER DHOU
= dha
ABDA ꯚ MEETEI MAYEK LETTER BHAM
= bha
Final consonants
ABDB ꯛ MEETEI MAYEK LETTER KOK LONSUM
= k
ABDC ꯜ MEETEI MAYEK LETTER LAI LONSUM
= l
ABDD ꯝ MEETEI MAYEK LETTER MIT LONSUM
= m
ABDE ꯞ MEETEI MAYEK LETTER PA LONSUM
= p


'''
